Refactor GitHub workflows

diff --git a/.github/workflows/reuse/selenium_tests.yml b/.github/workflows/reuse/selenium_tests.yml
--- a/.github/workflows/reuse/selenium_tests.yml
+++ b/.github/workflows/reuse/selenium_tests.yml
@@ -1,14 +1,28 @@
-name: Lint and Unit tests
+name: Reusable. Selenium tests
 
 on:
-  workflow_call:
+  push:
+    branches:
+      - main
   workflow_dispatch:
 
 jobs:
-  unit_tests:
-    runs-on: self-hosted
+  selenium_testing:
+    runs-on: ubuntu-latest
     environment:
       name: 'Local'
+
+    services:
+      selenium:
+        image: selenium/standalone-chrome:latest
+        options: >-
+          --health-cmd="curl -s http://localhost:4444/wd/hub/status | grep 'ready'"
+          --health-interval=10s
+          --health-timeout=5s
+          --health-retries=3
+          --shm-size=1gb
+        ports:
+          - 4444:4444
 
     steps:
       - uses: actions/checkout@v4
@@ -22,14 +36,6 @@ jobs:
         run: |
           npm clean-install
 
-      - name: Lint
-        run: |
-          npm run lint
-
-      - name: Unit tests
-        run: |
-          npm run test
-
       - name: Launch application locally
         env:
           AZURE_CLIENT_ID: ${{ secrets.AZURE_APPLICATION_TEST_CLIENT_ID }}
@@ -41,12 +47,23 @@ jobs:
           npm run dev > output/app_stdout.txt 2>&1 &
           sleep 20
 
+      - name: Run selenium tests
+        env:
+          SELENIUM_REMOTE_URL: http://localhost:4444/wd/hub      
+        run: |
+          npm run selenium 2>&1 | tee output/selenium_tests_stdout.txt
+          # Check the exit status of the previous command
+          if [ ${PIPESTATUS[0]} -ne 0 ]; then
+            echo "Selenium tests failed!"
+            exit 1  # Exit with a non-zero status to fail the job
+          fi
+
       # Upload screenshots as artifacts
-      - name: Upload outputs
+      - name: Upload screenshots
         if: always()      
         uses: actions/upload-artifact@v4
         with:
-          name: test-output
+          name: selenium-output
           path: output/
 
       - name: Stop the app
